export interface Project {
  id: number
  title: string
  description: string
  image: string
  category: string
  categoryLabel: string
  categoryColor: string
  technologies: string[]
  projectUrl: string
  externalUrl: string
}

export const projects: Project[] = [
  {
    id: 1,
    title: "Web4Crypto",
    description: "A startup made exclusively by me to promote my crypto-related developer services.",
    image: "/web4crypto.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["HTML", "CSS", "JavaScript", "NextJS"],
    projectUrl: "https://www.web4crypto.net/",
    externalUrl: "https://www.web4crypto.net/",
  },
  {
    id: 40,
    title: "SeekerNotes",
    description: "An aesthetic WIP notes-taking app for Windows & Linux written using React and wails (golang).",
    image: "/seekernotes.png",
    category: "web",
    categoryLabel: "Web|App Development",
    technologies: ["React", "Wails", "Golang"],
    categoryColor: "yellow",
    projectUrl: "https://seekernotesweb.pages.dev/",
    externalUrl: "https://seekernotesweb.pages.dev/",
  },
  {
    id: 41,
    title: "PsychMusic",
    description: "An extremely mathematically concept attempt at producing psychedelic-like visuals.",
    image: "/psychmusic.png",
    category: "web",
    categoryLabel: "Web Development",
    technologies: ["React"],
    categoryColor: "yellow",
    projectUrl: "https://psychmusic.pages.dev/",
    externalUrl: "https://psychmusic.pages.dev/",
  },
  {
    id: 52,
    title: "Crypfolio",
    description: "A SaaS to keep track of your crypto portfolio.",
    image: "/cryptfolio.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["HTML", "CSS", "React", "NextJS"],
    projectUrl: "https://crypfolio.pages.dev/",
    externalUrl: "https://crypfolio.pages.dev/",
  },
  {
    id: 16,
    title: "Hyflip",
    description: "Paid Bazaar/auction house flipper for Hypixel Skyblock.",
    image: "/bzs.png",
    category: "web",
    categoryLabel: "Web|Mod Development",
    technologies: ["React", "NextJS", "Golang", "Kotlin"],
    categoryColor: "red",
    projectUrl: "https://hyflip-website.vercel.app/",
    externalUrl: "https://hyflip-website.vercel.app/",
  },
  {
    id: 12,
    title: "DevSpoofGO",
    description: "A 5900+ LOC project for in-memory override DLL injection.",
    image: "/devspoofgo.png",
    category: "systems",
    categoryLabel: "Systems Development",
    technologies: ["Golang", "C++", "WinAPI", "Registry", "WMI"],
    categoryColor: "gray",
    projectUrl: "https://github.com/seekehr/DevSpoofGO",
    externalUrl: "https://github.com/seekehr/DevSpoofGO",
  },
  {
    id: 13,
    title: "DevSpoofTest",
    description: "A 1500+ LOC project for testing registry/WMI/WinAPI values.",
    image: "/devspoofgotest.png",
    category: "systems",
    categoryLabel: "Systems Development",
    categoryColor: "gray",
    technologies: ["Golang", "WinAPI", "Registry", "WMI"],
    projectUrl: "https://github.com/seekehr/DevSpoofGOTest",
    externalUrl: "https://github.com/seekehr/DevSpoofGOTest",
  },
  {
    id: 101,
    title: "NotesX",
    description: "A fully responsive self-hosted note-taking website.",
    image: "/notesx.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["HTML", "CSS", "JavaScript", "NextJS"],
    projectUrl: "https://github.com/seekehr/NotesX",
    externalUrl: "https://github.com/seekehr/NotesX",
  },
  {
    id: 2,
    title: "LoanTracker",
    description: "A SaaS-inspired website to track loans.",
    image: "/loanpicture.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["TypeScript", "ReactJS", "ExpressJS", "MySQL", "Redis"],
    projectUrl: "https://github.com/seekehr/LoanTracker",
    externalUrl: "https://youtu.be/LUcKv93m5lY?si=S5venFNsLeFufIN-",
  },
  {
    id: 9,
    title: "ZeqaStores",
    description: "A modern MERN-based e-commerce store.",
    image: "/zeqa.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["HTML", "TailwindCSS", "TypeScript", "ReactJS", "Express", "MySQL"],
    projectUrl: "https://youtu.be/SAvNmzm9Q64?si=RFBAfvZb1zeblvbK",
    externalUrl: "https://youtu.be/SAvNmzm9Q64?si=RFBAfvZb1zeblvbK",
  },
  {
    id: 3,
    title: "pfpm",
    description: "A pathfinding plugin for PocketMine-MP.",
    image: "/pathfinder.jpg",
    category: "plugin",
    categoryLabel: "Plugin Development",
    categoryColor: "red",
    technologies: ["PHP", "PocketMine-MP", "Pathfinding"],
    projectUrl: "https://github.com/seekehr/pfpm",
    externalUrl: "https://github.com/seekehr/pfpm",
  },
  {
    id: 11,
    title: "Moosik",
    description: "A music downloading and sharing website.",
    image: "/moosik.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["ReactJS", "TailwindCSS", "TypeScript", "ExpressJS", "MySQL"],
    projectUrl: "https://github.com/seekehr/moosik",
    externalUrl: "https://github.com/seekehr/moosik",
  },
  {
    id: 10,
    title: "NotTwitter",
    description: "Frontend of a Twitter-inspired social media website.",
    image: "/nottwitter.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["JSX", "TailwindCSS", "TypeScript", "ReactJS"],
    projectUrl: "https://github.com/seekehr/NotTwitterFront",
    externalUrl: "https://github.com/seekehr/NotTwitterFront",
  },
  {
    id: 4,
    title: "PassManager",
    description: "A password manager app inspired by KeePassXC.",
    image: "/passwordmanager.png",
    category: "cli",
    categoryLabel: "CLI",
    categoryColor: "yellow",
    technologies: ["JavaScript", "Node.js", "Argon2"],
    projectUrl: "https://github.com/seekehr/PasswordManager",
    externalUrl: "https://github.com/seekehr/PasswordManager",
  },
  {
    id: 7,
    title: "PoggitPE",
    description: "A plugin for downloading plugins from Poggit.",
    image: "/poggitpe.png",
    category: "plugin",
    categoryLabel: "Plugin Development",
    categoryColor: "red",
    technologies: ["PHP", "PocketMine-MP"],
    projectUrl: "https://github.com/seekehr/PoggitPE",
    externalUrl: "https://github.com/seekehr/PoggitPE",
  },
  {
    id: 8,
    title: "Portfolio",
    description: "This very website!",
    image: "/portfoliowebsite.png",
    category: "web",
    categoryLabel: "Web Development",
    categoryColor: "blue",
    technologies: ["HTML", "TailwindCSS", "JavaScript"],
    projectUrl: "https://github.com/seekehr/seekehr.github.io",
    externalUrl: "https://github.com/seekehr/seekehr.github.io",
  },
  {
    id: 14,
    title: "RedditBot",
    description: "Updated bot to automatically generate reddit videos.",
    image: "/redditvideomakerbotupdated.png",
    category: "cli",
    categoryLabel: "CLI Development",
    categoryColor: "yellow",
    technologies: ["Python", "Playwright", "FFmpeg"],
    projectUrl: "https://github.com/seekehr/RedditVideoMakerBot-Updated",
    externalUrl: "https://github.com/seekehr/RedditVideoMakerBot-Updated",
  },
]
